### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by srepollock** [srepollock/typescript-bootstrap#2]
- [x] TypeScript
- [x] Semantic Versioning
- [x] Travis CI
~- [ ] Cross env~
- [x] Mocha/Chai Unit testing
  - [x] Full unit testing
- [x] TypeDoc generation
- [x] Instanbul reporting
- [x] Coveralls online reporting
- [x] GitHub pages deployment
- [x] [GitHub releases](https://docs.travis-ci.com/user/deployment/releases/)
- [x] [NPM deployment](https://docs.travis-ci.com/user/deployment/npm/)

**Comment by srepollock** [comment]
NPM deployment will need to work with [npm scripts](https://docs.npmjs.com/misc/scripts)

**Comment by srepollock** [comment]
Update this repository to fit with the [Sunset Engine](https://github.com/srepollock/sunset-engine)

**Comment by srepollock** [comment]
Remove Babel as a compiler. I'll be using the base TypeScript compiler from here on.

**Comment by srepollock** [comment]
NPM releases are not completing. See [TravisCI build 56's](https://travis-ci.org/srepollock/ts-bootstrap/builds/493681450) log for details. Apparently not signed in as the correct user?

**Comment by srepollock** [comment]
See #13 and [Coveralls' issue](https://github.com/lemurheavy/coveralls-public/issues/1264) for more.

**Comment by srepollock** [comment]
Project v1.0.2 completed. All tasks complete
